# Generated by Django 6.0.6 on 2026-07-06 04:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('genre', models.CharField(choices=[('ACT', 'Action & Adventure'), ('SCI', 'Sci-Fi & Fantasy'), ('COM', 'Comedy & Drama'), ('HOR', 'Horror & Thriller')], max_length=10)),
                ('duration_minutes', models.PositiveIntegerField(default=120)),
                ('release_date', models.DateField()),
                ('poster_url', models.URLField(blank=True, default='https://via.placeholder.com/300x450')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cinema.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_date', models.DateField()),
                ('show_time', models.TimeField()),
                ('ticket_price', models.DecimalField(decimal_places=2, default=12.0, max_digits=6)),
                ('screen_number', models.PositiveIntegerField(default=1)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='cinema.movie')),
            ],
            options={
                'unique_together': {('movie', 'show_date', 'show_time', 'screen_number')},
            },
        ),
        migrations.CreateModel(
            name='SeatBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=15)),
                ('seat_numbers', models.CharField(max_length=100)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cinema.showtime')),
            ],
        ),
    ]
